name: github cicd for notejam

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-SCM:
    runs-on: label-1
    steps:
    - name: checkout SCM
      uses: actions/checkout@v2
  build-docker:
    needs: checkout-SCM
    runs-on: label-1
    steps:
      - name: Build the docker Image
        run: docker build -t notejam:$(date +%s) .
      - name: Tag the Image
        run: docker tag notejam:$(date +%s) arkdocr/jenkins:latest
        
      
  #push-docker-image:
  
  
  
  #deploy-to-GKE:
  
  
  
