name: github cicd for notejam

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-SCM:
    runs-on: label-1
    steps:
    - name: checkout SCM
      uses: actions/checkout@v2
  build-docker:
    needs: checkout-SCM
    runs-on: label-1
    steps:
      - name: Build the docker Image
        run: docker build -t notejam:master .
      - name: Tag the Image
        run: docker tag notejam:master arkdocr/jenkins:latest
        
      
  push-docker-image:
    needs: build-docker
    runs-on: label-1
    steps:
      - name: Login to dockerhub
        run: docker login -u "${{ secrets.CI_REGISTRY_USER }}" -p "${{ secrets.CI_REGISTRY_PASSWORD }}" ${{ secrets.CI_REGISTRY }}
        # env: 
         # CI_REGISTRY_USER: arkdocr
         # CI_REGISTRY_PASSWORD: 
         # CI_REGISTRY: docker.io      
      - name: Push the Image to Dockerhub
        run: docker push arkdocr/jenkins:latest
  
  
  deploy-to-GKE:
    needs: push-docker-image
    runs-on: notejam
    steps:
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
     # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        
      env:
        PROJECT_ID: ${{ secrets.GKE_PROJECT }}
        GKE_CLUSTER: cluster-1    # Add your cluster name here.
        GKE_ZONE: asia-south2-b   # Add your cluster zone here.
        #DEPLOYMENT_NAME: gke-test # Add your deployment name here.
        #IMAGE: static-site


    - name: deploy to GKE
      run: kubectl apply -f notejam-kube/mysql-deploy.yaml 

  
  
  
