name: github cicd for notejam

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-SCM:
    runs-on: label-1
    steps:
    - name: checkout SCM
      uses: actions/checkout@v2
  build-docker:
    needs: checkout-SCM
    runs-on: label-1
    steps:
      - name: Build the docker Image
        run: docker build -t notejam:master .
      - name: Tag the Image
        run: docker tag notejam:master arkdocr/jenkins:latest
        
      
  push-docker-image:
    needs: build-docker
    runs-on: label-1
    steps:
      - name: Login to dockerhub
        run: docker login -u "$CI_REGISTRY_USER" -p "secret.CI_REGISTRY_PASSWORD" $CI_REGISTRY
        env: 
          CI_REGISTRY_USER: arkdocr
         # CI_REGISTRY_PASSWORD: arkdocr007
          CI_REGISTRY: docker.io      
      - name: Push the Image to Dockerhub
        run: docker push arkdocr/jenkins:latest
  
  
  
  #deploy-to-GKE:
  
  
  
